swagger: "2.0"
info:
  description: "API para listar o Estado Civil."
  version: "1.0.0"
  title: "API Operadora Congenere"
  contact:
    email: "celuladigital@qualicorp.com.br"
host: "localhost:8082"
tags:
- name: "operadora-congenere"
  description: "Operadora Congenere"
schemes:
- "https"
- "http"
paths:
  /operadora-congenere:
    get:
      tags:
      - "operadora-congenere"
      summary: "Busca Operadora Congenere"
      description: "Realiza a busca das operadoras congenere cadastrados na base"
      operationId: "BuscaOperadoraCongenere"
      produces:
      - "application/json"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/OperadoraCongenere"
        400:
          description: "Error Message"
        404:
          description: "Nenhum estado civil encontrado."
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  OperadoraCongenere:
    type: "object"
    properties:
      id:
        type: "string"
      descricao:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"