swagger: '2.0'
info:
  description: 'Regra de Elegibilidade'
  version: 1.0.0
  title: regra_elegibilidade
  termsOfService: ''
  contact:
    email: dev-qualitech@qualicorp.com.br
host: 'devst2ap34:8082'
basePath: /regra_elegibilidade
schemes:
  - https
  - http
paths:
  /elegibilidade:
    post:
      summary: Regra de Elegibilidade
      description: 'Regra de Elegibilidade'
      operationId: elegibilidade
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações de entrada
          required: true
          schema:
            $ref: '#/definitions/input'
      responses:
        404:
          description: Item não localizado
        200:
          description: "Regra localizada"
          schema:
            $ref: '#/definitions/output'



definitions:
  input:
    type: object
    properties:
      inputData:
        type: string
        format: string
  output:
    type: object
    properties:
      outputData:
        type: string
        format: string
